# Generated by Django 4.2.14 on 2024-07-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
